# Spring
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wechat?createDatabaseIfNotExist=true
    username: sa
    password: Welcome1
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false

# Server
# 0072764.all123.net
server:
  port: 443
  ssl:
    key-store: .keystore
    key-alias: Clubs
    key-password: 12233368
    key-store-type: JKS
